#!/usr/bin/env python
from __future__ import print_function
import os

py=0
rb=0
pl=0
js=0
java=0
html=0
css=0
md=0
rst=0

def percentage(part, whole):
    #print("part:", part)
    #print("whole:", whole)
    if part == 0 and whole == 0:
        return "0.00"
    Percentage = 100 * float(part)/float(whole)
    #print("Percentage:", Percentage)
    return str("%0.2f"%(Percentage))
    # return str(Percentage)

#for root, dirs, files in os.walk(os.getcwd()):
for i in list(filter(None, [i.split("\n")[0] for i in os.listdir(os.getcwd())])):
    #for i in files:
    if i.endswith('.py'):
        py+=1
    elif i.endswith('.rb'):
        rb+=1
    elif i.endswith('.pl'):
        pl+=1
    elif i.endswith('.js'):
        js+=1
    elif i.endswith('.java'):
        java+=1
    elif i.endswith('.html') or i.endswith('.htm'):
        html+=1
    elif i.endswith('.css'):
        css+=1
    elif i.endswith('.md'):
        md+=1
    elif i.endswith('.rst'):
        rst+=1

numbers = py+rb+pl+js+java+html+css+md+rst
#print("numbers:", numbers)

print(
    percentage(py, numbers),
    percentage(rb, numbers),
    percentage(pl, numbers),
    percentage(js, numbers),
    percentage(java, numbers),
    percentage(html, numbers),
    percentage(css, numbers),
    percentage(md, numbers),
    percentage(rst, numbers),
)
